"""Estoque esperado e inventário físico."""
from alembic import op
import sqlalchemy as sa
revision="0002"; down_revision="0001"

def upgrade():
 op.create_table("expected_stocks",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("cellar_id",sa.Integer(),sa.ForeignKey("cellars.id"),nullable=False),sa.Column("position_id",sa.Integer(),sa.ForeignKey("positions.id"),nullable=False),sa.Column("wine_id",sa.Integer(),sa.ForeignKey("wines.id"),nullable=False),sa.Column("quantity",sa.Integer(),nullable=False),sa.Column("updated_at",sa.DateTime(),nullable=False),sa.Column("updated_by_id",sa.Integer(),sa.ForeignKey("users.id"),nullable=False),sa.UniqueConstraint("position_id","wine_id",name="uq_stock_position_wine"),sa.CheckConstraint("quantity >= 0",name="ck_stock_nonnegative"))
 op.create_table("stock_history",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("stock_id",sa.Integer(),sa.ForeignKey("expected_stocks.id")),sa.Column("cellar_id",sa.Integer(),sa.ForeignKey("cellars.id"),nullable=False),sa.Column("position_id",sa.Integer(),sa.ForeignKey("positions.id"),nullable=False),sa.Column("wine_id",sa.Integer(),sa.ForeignKey("wines.id"),nullable=False),sa.Column("quantity_before",sa.Integer(),nullable=False),sa.Column("quantity_after",sa.Integer(),nullable=False),sa.Column("kind",sa.String(20),nullable=False),sa.Column("reason",sa.Text(),nullable=False),sa.Column("user_id",sa.Integer(),sa.ForeignKey("users.id"),nullable=False),sa.Column("created_at",sa.DateTime(),nullable=False),sa.CheckConstraint("quantity_before >= 0 AND quantity_after >= 0",name="ck_history_nonnegative"))
 op.create_table("inventories",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("name",sa.String(150),nullable=False),sa.Column("cellar_id",sa.Integer(),sa.ForeignKey("cellars.id"),nullable=False),sa.Column("status",sa.String(30),nullable=False),sa.Column("created_by_id",sa.Integer(),sa.ForeignKey("users.id"),nullable=False),sa.Column("created_at",sa.DateTime(),nullable=False),sa.Column("started_at",sa.DateTime()),sa.Column("completed_at",sa.DateTime()),sa.Column("approved_at",sa.DateTime()),sa.Column("approved_by_id",sa.Integer(),sa.ForeignKey("users.id")),sa.Column("notes",sa.Text()))
 op.create_table("inventory_scopes",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("inventory_id",sa.Integer(),sa.ForeignKey("inventories.id",ondelete="CASCADE"),nullable=False),sa.Column("position_id",sa.Integer(),sa.ForeignKey("positions.id"),nullable=False),sa.Column("first_finished_at",sa.DateTime()),sa.Column("second_finished_at",sa.DateTime()),sa.Column("recount_finished_at",sa.DateTime()),sa.Column("first_user_id",sa.Integer(),sa.ForeignKey("users.id")),sa.Column("lock_token",sa.String(64)),sa.Column("lock_user_id",sa.Integer(),sa.ForeignKey("users.id")),sa.Column("version",sa.Integer(),nullable=False),sa.UniqueConstraint("inventory_id","position_id",name="uq_inventory_position"))
 op.create_table("inventory_snapshots",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("scope_id",sa.Integer(),sa.ForeignKey("inventory_scopes.id",ondelete="CASCADE"),nullable=False),sa.Column("wine_id",sa.Integer(),sa.ForeignKey("wines.id"),nullable=False),sa.Column("quantity",sa.Integer(),nullable=False),sa.UniqueConstraint("scope_id","wine_id",name="uq_snapshot_wine"),sa.CheckConstraint("quantity >= 0",name="ck_snapshot_nonnegative"))
 op.create_table("inventory_counts",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("inventory_id",sa.Integer(),sa.ForeignKey("inventories.id",ondelete="CASCADE"),nullable=False),sa.Column("position_id",sa.Integer(),sa.ForeignKey("positions.id"),nullable=False),sa.Column("wine_id",sa.Integer(),sa.ForeignKey("wines.id"),nullable=False),sa.Column("stage",sa.String(20),nullable=False),sa.Column("quantity",sa.Integer(),nullable=False),sa.Column("user_id",sa.Integer(),sa.ForeignKey("users.id"),nullable=False),sa.Column("device",sa.String(120)),sa.Column("counted_at",sa.DateTime(),nullable=False),sa.Column("observation",sa.Text()),sa.Column("version",sa.Integer(),nullable=False),sa.UniqueConstraint("inventory_id","position_id","wine_id","stage",name="uq_count_stage"),sa.CheckConstraint("quantity >= 0",name="ck_count_nonnegative"))

def downgrade():
 for name in ("inventory_counts","inventory_snapshots","inventory_scopes","inventories","stock_history","expected_stocks"): op.drop_table(name)
